import Head from "next/head";

export default function Home() {
  return (
    <div>
      <Head>
        <title>NextEcom</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1 className="text-3xl text-red-300 font-bold underline">NextEcom</h1>
    </div>
  );
}
